import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Localization from "expo-localization";
import { I18n } from "i18n-js";

const i18n = new I18n();

i18n.translations = {
  pt: {
    mensagemSistema: {
      carregando: "Carregando...",
      sucesso: "Sucesso!",
      erro: "Ops! Algo deu errado",
      confirmar: "Confirmar",
      cancelar: "Cancelar",
    },
    index: {
      adicionarCard: "Crie seu primeiro flashcard",
      finalLista: "Isso é tudo por enquanto! 🎉",
      bemVindo: "Bem-vindo ao FlashCards",
      bemVindoDescricao: "Comece adicionando suas primeiras palavras",
    },
    layout: {
      configuracao: "Configurações",
      indexTitulo: "FlashCards",
      adicionarTitulo: "Novo Flashcard",
      listaPalavrasTitulo: "Meus Flashcards",
      listaCategoriasTitulo: "Categorias",
      resumoTitulo: "Meu Progresso",
      tabInicio: "Início",
      tabLista: "Lista",
      tabCategorias: "Categorias",
      tabResumo: "Progresso",
    },
    adicionar: {
      alerta: "Preencha todos os campos obrigatórios",
      tituloFrente1: "Frente do Card",
      tituloFrente2: "Pergunta ou Termo",
      requerido: "Obrigatório",
      exemploPalavra: "Ex: Qual a capital do Brasil?",
      tituloVerso1: "Verso do Card",
      tituloVerso2: "Resposta ou Definição",
      exemploResposta: "Ex: Brasília",
      botaoSalvar: "SALVAR CARD",
      botaoSalvarEditando: "ATUALIZAR CARD",
      categoria: "Categoria",
      modoSelecionar: "Selecionar categoria",
      modoAdicionar: "Criar nova categoria",
      placeholderNovaCategoria: "Nome da nova categoria",
      botaoAddCategoria: "ADICIONAR",
      semCategoria: "Sem categoria",
      sucessoAdicionar: "Card adicionado com sucesso!",
      sucessoEditar: "Card atualizado com sucesso!",
      erroAdicionar: "Erro ao adicionar card",
      erroEditar: "Erro ao atualizar card",
    },
    listaDePalavras: {
      listaVazia: "Nenhum card encontrado",
      listaVaziaDescricao: "Toque no + para criar seu primeiro card",
      buscarPlaceholder: "Buscar cards...",
      deleteConfirmacaoTitulo: "Excluir Card",
      deleteConfirmacaoTexto: "Tem certeza que deseja excluir este card?",
      deleteSucesso: "Card excluído com sucesso",
      deleteErro: "Erro ao excluir card",
      formTexto: "Editar Card",
      totalCards: "{{count}} card",
      totalCards_plural: "{{count}} cards",
      filtrarPorCategoria: "Filtrar por categoria",
      todasCategorias: "Todas as categorias",
    },
    listaDeCategorias: {
      placeholderBusca: "Buscar categorias...",
      tituloSecao: "Suas Categorias",
      deleteConfirmacaoTitulo: "Excluir Categoria",
      deleteConfirmacaoTexto: "Ao excluir '{{categoria}}', {{count}} card será movido para 'Sem categoria'",
      deleteConfirmacaoTexto_plural: "Ao excluir '{{categoria}}', {{count}} cards serão movidos para 'Sem categoria'",
      editarCategoria: "Editar Categoria",
      cancelar: "Cancelar",
      salvar: "Salvar",
      categoriaVazia: "Digite um nome para a categoria",
      categoriaExistente: "Já existe uma categoria com este nome",
      naoDeletarSemCategoria: "A categoria 'Sem categoria' não pode ser excluída",
      naoEditarSemCategoria: "A categoria 'Sem categoria' não pode ser editada",
      categoriaDeletada: "Categoria excluída com sucesso",
      categoriaEditada: "Categoria atualizada com sucesso",
      erroDeletar: "Erro ao excluir categoria",
      erroEditar: "Erro ao atualizar categoria",
      novaCategoria: "Nova Categoria",
      editarCategoriaPlaceholder: "Nome da categoria",
      totalCards: "{{count}} card",
      totalCards_plural: "{{count}} cards",
      semCards: "Nenhum card",
    },
    resumo: {
      titulo: "Meu Progresso",
      semErrosTitulo: "Nenhum erro ainda! 🎉",
      semErrosSubtitulo: "Continue praticando para ver suas estatísticas aqui",
      palavrasComErro: "Palavras com erro",
      totalErros: "Total de erros",
      frequenciaErros: "Frequência de Erros",
      estatisticas: "Estatísticas",
      progressoGeral: "Progresso Geral",
      cardsEstudados: "Cards estudados",
      taxaAcerto: "Taxa de acerto",
      melhorarFoco: "Foque em melhorar",
      praticarMais: "Praticar estas palavras",
      excelente: "Excelente progresso!",
      bom: "Bom trabalho!",
      continue: "Continue assim!",
    },
    configuracao: {
      titulo: "Configurações",
      cabecalho: "Lembretes de Estudo",
      lembrete: "Lembretes diários",
      lembreteTexto: "Receba notificações para estudar todos os dias",
      horarioLembrete: "Horário do lembrete",
      politica: "Política de Privacidade",
      atualizacao: "Sobre o App",
      escolhaHorario: "Escolha o horário",
      cancelar: "Cancelar",
      confirmar: "Confirmar",
      infoVersaoTitulo: "Sobre esta versão",
      versao: "Versão",
      ultimaAtualizacao: "Última atualização",
      novidades: "Novidades",
      alertaPermissaoTitle: "Permissão Necessária",
      alertaPermissaoTexto: "Para enviar lembretes, precisamos da permissão de notificações",
      alertaSucessoTitle: "Tudo certo!",
      alertaSucessoTextoAtivado: "Lembretes ativados com sucesso",
      alertaSucessoTextoDesativado: "Lembretes desativados",
      alertaErro: "Não foi possível alterar as configurações",
      erroAbrirLink: "Não foi possível abrir o link",
      erroPolitica: "Erro ao abrir a política de privacidade",
      horarioDefinido: "Horário atualizado com sucesso",
      idiomaAlteradoTitle: "Idioma alterado",
      idiomaAlteradoTexto: "O app agora está em português",
      idioma: "Idioma",
      portugues: "Português",
      ingles: "English",
      tema: "Tema",
      temaClaro: "Claro",
      temaEscuro: "Escuro",
      temaSistema: "Seguir sistema",
      notificacoes: "Notificações",
      gerais: "Gerais",
      sobre: "Sobre",
      feedback: "Enviar Feedback",
      avaliarApp: "Avaliar o App",
      compartilhar: "Compartilhar App",
    },
    estudo: {
      titulo: "Modo Estudo",
      comecar: "Começar Estudo",
      continuar: "Continuar",
      novoEstudo: "Novo Estudo",
      cardsParaEstudar: "{{count}} card para estudar",
      cardsParaEstudar_plural: "{{count}} cards para estudar",
      acertou: "Acertou! 🎉",
      errou: "Quase lá! 💪",
      mostrarResposta: "Mostrar resposta",
      proximoCard: "Próximo card",
      finalizar: "Finalizar estudo",
      resultado: "Resultado do Estudo",
      totalAcertos: "Acertos: {{acertos}}/{{total}}",
      porcentagemAcerto: "{{porcentagem}}% de acerto",
      excelente: "Excelente! 🏆",
      bom: "Bom trabalho! 👍",
      precisaMelhorar: "Vamos praticar mais! 📚",
      estudarNovamente: "Estudar novamente",
      voltarLista: "Voltar para lista",
    },
    categorias: {
      todas: "Todas",
      semCategoria: "Sem categoria",
      adicionarCategoria: "Adicionar Categoria",
    }
  },
  en: {
    mensagemSistema: {
      carregando: "Loading...",
      sucesso: "Success!",
      erro: "Oops! Something went wrong",
      confirmar: "Confirm",
      cancelar: "Cancel",
    },
    index: {
      adicionarCard: "Create your first flashcard",
      finalLista: "That's all for now! 🎉",
      bemVindo: "Welcome to FlashCards",
      bemVindoDescricao: "Start by adding your first words",
    },
    layout: {
      configuracao: "Settings",
      indexTitulo: "FlashCards",
      adicionarTitulo: "New Flashcard",
      listaPalavrasTitulo: "My Flashcards",
      listaCategoriasTitulo: "Categories",
      resumoTitulo: "My Progress",
      tabInicio: "Home",
      tabLista: "List",
      tabCategorias: "Categories",
      tabResumo: "Progress",
    },
    adicionar: {
      alerta: "Please fill all required fields",
      tituloFrente1: "Card Front",
      tituloFrente2: "Question or Term",
      requerido: "Required",
      exemploPalavra: "E.g.: What is Brazil's capital?",
      tituloVerso1: "Card Back",
      tituloVerso2: "Answer or Definition",
      exemploResposta: "E.g.: Brasília",
      botaoSalvar: "SAVE CARD",
      botaoSalvarEditando: "UPDATE CARD",
      categoria: "Category",
      modoSelecionar: "Select category",
      modoAdicionar: "Create new category",
      placeholderNovaCategoria: "New category name",
      botaoAddCategoria: "ADD",
      semCategoria: "No category",
      sucessoAdicionar: "Card added successfully!",
      sucessoEditar: "Card updated successfully!",
      erroAdicionar: "Error adding card",
      erroEditar: "Error updating card",
    },
    listaDePalavras: {
      listaVazia: "No cards found",
      listaVaziaDescricao: "Tap + to create your first card",
      buscarPlaceholder: "Search cards...",
      deleteConfirmacaoTitulo: "Delete Card",
      deleteConfirmacaoTexto: "Are you sure you want to delete this card?",
      deleteSucesso: "Card deleted successfully",
      deleteErro: "Error deleting card",
      formTexto: "Edit Card",
      totalCards: "{{count}} card",
      totalCards_plural: "{{count}} cards",
      filtrarPorCategoria: "Filter by category",
      todasCategorias: "All categories",
    },
    listaDeCategorias: {
      placeholderBusca: "Search categories...",
      tituloSecao: "Your Categories",
      deleteConfirmacaoTitulo: "Delete Category",
      deleteConfirmacaoTexto: "By deleting '{{categoria}}', {{count}} card will be moved to 'No category'",
      deleteConfirmacaoTexto_plural: "By deleting '{{categoria}}', {{count}} cards will be moved to 'No category'",
      editarCategoria: "Edit Category",
      cancelar: "Cancel",
      salvar: "Save",
      categoriaVazia: "Enter a category name",
      categoriaExistente: "A category with this name already exists",
      naoDeletarSemCategoria: "The 'No category' category cannot be deleted",
      naoEditarSemCategoria: "The 'No category' category cannot be edited",
      categoriaDeletada: "Category deleted successfully",
      categoriaEditada: "Category updated successfully",
      erroDeletar: "Error deleting category",
      erroEditar: "Error updating category",
      novaCategoria: "New Category",
      editarCategoriaPlaceholder: "Category name",
      totalCards: "{{count}} card",
      totalCards_plural: "{{count}} cards",
      semCards: "No cards",
    },
    resumo: {
      titulo: "My Progress",
      semErrosTitulo: "No errors yet! 🎉",
      semErrosSubtitulo: "Keep practicing to see your statistics here",
      palavrasComErro: "Words with errors",
      totalErros: "Total errors",
      frequenciaErros: "Error Frequency",
      estatisticas: "Statistics",
      progressoGeral: "Overall Progress",
      cardsEstudados: "Cards studied",
      taxaAcerto: "Success rate",
      melhorarFoco: "Focus on improving",
      praticarMais: "Practice these words",
      excelente: "Excellent progress!",
      bom: "Good job!",
      continue: "Keep it up!",
    },
    configuracao: {
      titulo: "Settings",
      cabecalho: "Study Reminders",
      lembrete: "Daily reminders",
      lembreteTexto: "Receive notifications to study every day",
      horarioLembrete: "Reminder time",
      politica: "Privacy Policy",
      atualizacao: "About App",
      escolhaHorario: "Choose time",
      cancelar: "Cancel",
      confirmar: "Confirm",
      infoVersaoTitulo: "About this version",
      versao: "Version",
      ultimaAtualizacao: "Last update",
      novidades: "What's new",
      alertaPermissaoTitle: "Permission Required",
      alertaPermissaoTexto: "To send reminders, we need notification permission",
      alertaSucessoTitle: "All set!",
      alertaSucessoTextoAtivado: "Reminders enabled successfully",
      alertaSucessoTextoDesativado: "Reminders disabled",
      alertaErro: "Could not change settings",
      erroAbrirLink: "Could not open link",
      erroPolitica: "Error opening privacy policy",
      horarioDefinido: "Time updated successfully",
      idiomaAlteradoTitle: "Language changed",
      idiomaAlteradoTexto: "The app is now in English",
      idioma: "Language",
      portugues: "Portuguese",
      ingles: "English",
      tema: "Theme",
      temaClaro: "Light",
      temaEscuro: "Dark",
      temaSistema: "Follow system",
      notificacoes: "Notifications",
      gerais: "General",
      sobre: "About",
      feedback: "Send Feedback",
      avaliarApp: "Rate App",
      compartilhar: "Share App",
    },
    estudo: {
      titulo: "Study Mode",
      comecar: "Start Study",
      continuar: "Continue",
      novoEstudo: "New Study",
      cardsParaEstudar: "{{count}} card to study",
      cardsParaEstudar_plural: "{{count}} cards to study",
      acertou: "Correct! 🎉",
      errou: "Almost there! 💪",
      mostrarResposta: "Show answer",
      proximoCard: "Next card",
      finalizar: "Finish study",
      resultado: "Study Result",
      totalAcertos: "Correct: {{acertos}}/{{total}}",
      porcentagemAcerto: "{{porcentagem}}% correct",
      excelente: "Excellent! 🏆",
      bom: "Good job! 👍",
      precisaMelhorar: "Let's practice more! 📚",
      estudarNovamente: "Study again",
      voltarLista: "Back to list",
    },
    categorias: {
      todas: "All",
      semCategoria: "No category",
      adicionarCategoria: "Add Category",
    }
  },
};

// Configuração inicial
i18n.fallbacks = true;
i18n.defaultLocale = "pt";
i18n.enableFallback = true;

// Função para inicializar o idioma
export const initI18n = async () => {
  try {
    const storedLang = await AsyncStorage.getItem("appLanguage");
    if (storedLang) {
      i18n.locale = storedLang;
    } else {
      const systemLocale = Localization.locale || "pt";
      i18n.locale = systemLocale.startsWith("pt") ? "pt" : "en";
    }
  } catch (error) {
    console.warn("Erro ao carregar idioma:", error);
    i18n.locale = "pt";
  }
};

// Função para mudar o idioma
export const changeLanguage = async (newLang) => {
  try {
    await AsyncStorage.setItem("appLanguage", newLang);
    i18n.locale = newLang;
    return true;
  } catch (error) {
    console.warn("Erro ao salvar idioma:", error);
    return false;
  }
};

// Função para obter idioma atual
export const getCurrentLanguage = () => {
  return i18n.locale;
};

// Inicializa imediatamente
initI18n();

export default i18n;